### ISSUE TITLE
how to use meteor-tabular when i using DDP!!!

### ISSUE THREAD

**Issue by chaigon** [aldeed/meteor-tabular#365]
I use meteor-tabular as usual, but I get an error:
`I20161128-10:34:13.049(8)? Exception from sub tabular_getInfo id ZaxT5aqxPXxqCuSc3 Error: must use ordered observe (ie, 'addedBefore' instead of 'added') with skip or limit
I20161128-10:34:13.052(8)?     at [object Object]._.extend.observeChanges (packages/minimongo/minimongo.js:325:1)
I20161128-10:34:13.053(8)?     at Subscription._handler (packages/aldeed_tabular/server/tabular.js:153:1)
I20161128-10:34:13.053(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20161128-10:34:13.054(8)?     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
I20161128-10:34:13.054(8)?     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
I20161128-10:34:13.056(8)?     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
I20161128-10:34:13.056(8)?     at packages/ddp-server/livedata_server.js:551:43`

Does anyone use meteor-tabular successfully with DDP?

**Comment by aldeed** [comment]
I'm not sure what you mean by "with DDP"? Your table collection is using a non-default connection?
