### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by philcruz** [aldeed/meteor-tabular#373]
I added the meteor package and did npm install. When I start the app I get this error

/Users/phil/Projects/lets-eat/node_modules/datatables.net-bs/css/dataTables.bootstrap.css:1
(function (exports, require, module, __filename, __dirname) { table.dataTable {
                                                                              ^

> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at npmRequire (/Users/phil/Projects/lets-eat/.meteor/local/build/programs/server/npm-require.js:133:10)
>     at Module.Mp.useNode (packages/modules-runtime.js:493:20)
>     at fileEvaluate (packages/modules-runtime.js:180:20)
> Exited with code: 1
> Your application is crashing. Waiting for file change.

What could be the problem?

**Comment by philcruz** [comment]
I got around this error by restructuring the code in /imports directory structure. But now I'm running into #91 

I'll close this issue and track that issue.
